name: ARM64

on:
  schedule:
    - cron:  '0 5 * * 0'
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - '.github/workflows/release.yaml'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/metadata-action@v3
        id: meta
        name: Docker meta
        with:
          images: ghcr.io/stiviik/go-modules-http-proxy
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - uses: docker/setup-qemu-action@v1
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/login-action@v1 
        name: Login to ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.6.1
        with:
          context: './'
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}